name: Build APK con Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Instalar Buildozer y Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Construir el APK con Buildozer
      run: buildozer android debug

    - name: Guardar el APK
      uses: actions/upload-artifact@v4
      with:
        name: aplicacion-apk
        path: bin/*.apk
